
graph RL
    B[pandas] --> A[C:\Programme..\some_path\...]
    C[matplotlib] --> A
    D[jupyter notebook] --> A
    E[geopandas] --> A
    A --> X[Project A]
    A --> Y[Project B]
    A --> Z[Projekt C]

    


