sequenceDiagram
    participant A as Server
    participant B as Lokal
    participant C as Session

    A->> B: modul installieren
    Note over A,B: Modul ist nun Einsetzbar
    B->> C: modul laden
    Note over B,C: Modul kommt zum Einsatz