graph TB  
    A[no module name 'pandas']
    A --> B{{"Du musst 'pandas' installieren! Weisst du wie das geht?"}}
    B -->|Ja| Z
    B -->|Nein| F{{"Ist ein freier Terminal verfügbar (1)?"}}
    F --> |Nein|K[Neuer Terminal starten]
    F --> |Ja|M{{"Ist die richtige Environment aktiviert? (2)"}}
    K --> T
    M -->|Nein|T["Environment aktivieren (3)"]
    M --> |Ja|Z["'pandas' installieren (4)"]
    T --> Z
    Z --> X[In JupyterLab Weiter arbeiten]



